---
title: "Practical Machine Learning project"
output: html_document
---

This is Practical Machine Learning project.

At first we load the necessary libraries:

```{r}
library(caret); library(kernlab);library(doParallel);library(foreach);
```

Then we load the trainings data:
```{r}
  training <- read.csv("C:/Users/Viktor/Documents/R/machinelearning/pml-training.csv", na.strings=c("#DIV/0!","NA",""))
  evaluation <- read.csv("C:/Users/Viktor/Documents/R/machinelearning/pml-testing.csv", na.strings=c("#DIV/0!","NA",""))
```

Subset the data for trainig and skip username and date rows
```{r}
feature_set <- training[,6:160]
evaluation_set <- evaluation[,6:160]
```


Preprocess the data:
Convert all features to numeric and remove all rows with missing data
```{r}
feature_set<-feature_set[,colSums(is.na(feature_set)) == 0]
evaluation_set<-evaluation_set[,colSums(is.na(evaluation_set)) == 0]

for(i in c(1:ncol(feature_set))) {feature_set[,i] = as.numeric((feature_set[,i]))}
for(i in c(1:ncol(evaluation_set))) {evaluation_set[,i] = as.numeric((evaluation_set[,i]))}


```


Split the data to training and testing sets
```{r}
set.seed(96)
idx <- createDataPartition(y=feature_set$classe, p=0.75, list=FALSE )
training_set <- feature_set[idx,]
testing_set <- feature_set[-idx,]
```


Use Random Forests
```{r}
registerDoParallel()
modelFit <- train(y=as.factor(training_set$classe), x=training_set[-ncol(training_set)], tuneGrid=data.frame(mtry=3), trControl=trainControl(method="none"), method="parRF")
```


Confusion Matrix for Test set
```{r}
prediction <- predict(modelFit, newdata=testing_set)
confusionMatrix(prediction, testing_set$classe)
```


```{r, echo=FALSE}
print(plot(varImp(modelFit, scale = FALSE)))
```

